name = "BLRemoteDataClient"
uuid = "fb54281b-2328-43f0-88b5-aa616f75139e"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.2.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

# Add OpenSSL_jll as a compat bouded weak dependency to be more amenable to use
# with Plots.jl from a "stacked" environment (because Plots -> FFMPEG ->
# OpenSSL -> OpenSSL_jll<3.0).
[weakdeps]
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"

[compat]
OpenSSL_jll = "1.1"
