name = "BLRemoteDataClient"
uuid = "fb54281b-2328-43f0-88b5-aa616f75139e"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.1.1"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

# Add OpenSSL_jll as a compat bouded weak dependency to be more amenable to use
# with Plots.jl from a "stacked" environment (because Plots -> FFMPEG ->
# OpenSSL -> OpenSSL_jll<3.0).
[weakdeps]
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"

[compat]
OpenSSL_jll = "1.1"
